Fix "www/js/Plaisio/Table/OverviewTable.ts(954,20): error TS2774: This condition will always return true since the function is always defined. Did you mean to call it instead?".